language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U setuptools   # Fix for https://travis-ci.org/scriptotek/otsrdflib/jobs/152446727
  - python setup.py install
  - pip install Pygments collective.checkdocs

script:
  - py.test
  - python setup.py checkdocs

